### ISSUE TITLE
Guard::Compass failed to achieve its <run_on_change>, exception 

### ISSUE THREAD

**Issue by sjoonk** [oliamb/guard-compass#6]
When I run guard this error occurred:

ERROR: Guard::Compass failed to achieve its <run_on_change>, exception was:
NoMethodError: undefined method `execute' for nil:NilClass
/opt/local/lib/ruby/gems/1.8/gems/guard-compass-0.0.6/lib/guard/compass.rb:47:in`run_on_change'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:106:in `send'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:106:in`supervised_task'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:84:in `run_on_change'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:80:in`each'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:80:in `run_on_change'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:95:in`run'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:79:in `run_on_change'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:50:in`start_reactor'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:46:in `loop'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:46:in`start_reactor'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:45:in `initialize'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:45:in`new'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:45:in `start_reactor'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:40:in`initialize'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listeners/darwin.rb:5:in `initialize'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:19:in`new'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/listener.rb:19:in `select_and_init'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:21:in`setup'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard.rb:32:in `start'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/lib/guard/cli.rb:17:in`start'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
/opt/local/lib/ruby/gems/1.8/gems/guard-0.7.0/bin/guard:6
/opt/local/bin/guard:19:in`load'
/opt/local/bin/guard:19

**Comment by lenart** [comment]
This happened to me when settings in either Guardfile or config.rb were invalid. Try reverting to defaults and change one setting at the time and see which ones breaks the code.

**Comment by KasperTidemann** [comment]
Just bumping this one. Any news? I am getting sort of the same error, except for the fact that my exception is `Compass::Error: Nothing to compile. If you're trying to start a new project, you have left off the directory argument.` (and not the undefined method one).

**Comment by cbfrance** [comment]
If you are having this problem: 
- Make sure you check settings in both the Guardfile AND in the config.rb  (it will give this error if the compass config is pointing to the wrong stylesheets directory) 
- make sure `compass watch` works
- make sure your regex is good in the Guardfile

I was confused by this error until I realized that compass watch did not work, and the problem was not Guard-related.

**Comment by zx1986** [comment]
check this out: https://github.com/guard/guard-compass/issues/10

in tmux, I run `compass watch`, then run `guard` in other panel at the same time.

here is my Guardfile:

``` ruby
guard 'livereload' do
  watch(%r{.+\.(php|html|js|css)$})
end

#guard 'compass' do
#  watch(/assets\/sass\/(.*)\.s[ac]ss/)
#end
```

things work fine.

**Comment by robwierzbowski** [comment]
Today I updated guard-compass and I'm now also getting the OP's error. Compass errors that normally would have output to terminal are now causing Compass to be fired. Didn't change .Guardfile or compass.rb, just updated.

**Comment by cbfrance** [comment]
Upgraded from/to which versions?

Unfortunately the error is very vague, and seems common — but so far I think there is no confirmation of a bug in this thread.

**Comment by rymai** [comment]
Hi guys, as @unthinkingly said, please:
- Update guard and guard-compass (`bundle update guard guard-compass`)
- Make sure you check settings in both the `Guardfile` AND in the `config.rb` (it will give this error if the compass config is pointing to the wrong stylesheets directory)
- Make sure `compass watch` works
- Make sure your regex is good in the Guardfile

If you still have any issues, please [continue the discussion in the maintained repository](https://github.com/guard/guard-compass/issues/10): guard#10

**Comment by rymai** [comment]
@sjoonk could you close this issue and [continue the discussion in the maintained repository](https://github.com/guard/guard-compass/issues/10) (guard#10) if needed.

Thank you!

**Comment by rymai** [comment]
Ping!
